export const primaryColor = "#bada55"
export const accentColor = "#eeeeee"
export const fontPrimaryColor = "#333333"
export const fontSecondaryColor = "#666666"
export const white = "#ffffff"
export const tagColor = "#aaaaaa"
